---
title: "Class1109_yx2858"
author: "Yueyi Xu"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit a model!!!

```{r}
fit = 
  nyc_airbnb |>
  lm(price ~ stars + borough, data = _)
```


Let's look at the fit

```{r}
fit
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

tidy up the output instead

```{r}
fit |>
  broom::glance()
```

tidy up the coefficient

```{r}
fit |> 
  broom::tidy() |>
  mutate(term = str_replace(term, "borough", "Borough: ")) |>
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```


### Fit another model

```{r}
nyc_airbnb = 
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
  fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit |>
  broom::tidy()
```


## Quick look at diagnostics

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-100, 500)
```

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = borough, y = resid)) +
  geom_violin()
```

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```


## Hypothesis test for categorical predictor

fit a "null" and "alternative" model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) |>
  broom::tidy()
```


## Borough-level differences

```{r}
fit =
  nyc_airbnb |>
  lm(price ~ stars * borough + room_type * borough, data = _)

fit |>
  broom::tidy()
```

```{r}
airbnb_lm = function(df) {
  lm(price ~stars + room_type, data = df)
}


nyc_airbnb |>
  nest(df = -borough) |>
  mutate(
    models = map(df, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)
  ) |>
  select(borough, results) |>
  unnest(results) |>
  select(borough, term, estimate) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |>
  knitr::kable(digits = 2)
```


## Homicides in Baltimore

```{r}
baltimore_df =
  read_csv("homicide-data.csv") |>
  filter(city == "Baltimore") |>
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age)
  ) |>
  select(resolved, victim_age, victim_race, victim_sex)
```


fitting a logistic regression

```{r}
fit_logistics = 
  baltimore_df |>
  glm(
    resolved ~ victim_age + victim_race + victim_sex,
    data = _,
    family = binomial()
  )
```

look at model results

```{r}
fit_logistics |>
  broom::tidy() |>
  mutate(OR = exp(estimate)) |>
  select(term, estimate, OR)
```


